services:
    
  caddy-gen:
    container_name: caddy-gen
    image: wemakeservices/caddy-gen:master
    ports:
      - 443:443
      - 80:80
    environment:
      CADDY_SNIPPET: /etc/caddy/caddy.snippet
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # needs socket to read events
      - ./caddy/data:/data/caddy
      - ./caddy/etc:/etc/caddy
      - ./caddy/config:/config/caddy
    networks:
      - telemt-network
    restart: unless-stopped
      
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_DISABLE_CONTAINERS: /amnezia-awg
      WATCHTOWER_NOTIFICATION_URL: telegram://${TELEGRAM_BOT_TOKEN}@telegram?chats=${CHAT_ID}
    restart: unless-stopped

  telemt:
    image: ghcr.io/telemt/telemt:latest
    build: .
    container_name: telemt
    ports:
      - 4455:4455 # proxy
      - 9091:9091 # api
      - 9090:9090 # metrics 
    working_dir: /run/telemt
    volumes:
      - ./telemt:/run/telemt
    environment:
      - RUST_LOG=info
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - telemt-network
    restart: unless-stopped
    
  telemt-panel:
    image: ghcr.io/amirotin/telemt_panel:latest
    container_name: telemt-panel
    ports:
      - 8080:8080 
    volumes:
      - ./telemt-panel:/etc/telemt-panel
      - ./telemt:/run/telemt:rw
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - caddy-gen
      - telemt
    networks:
      - telemt-network
    restart: unless-stopped
    labels:
      virtual.host: telemt.${DOMAIN}
      virtual.port: 8080
      virtual.tls-email: ${TLS_EMAIL}
      
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    restart: unless-stopped
    
  prometheus-amnezia-exporter:
    image: fixfever/prometheus-amnezia-exporter:latest
    container_name: prometheus-amnezia-exporter
    ports:
      - 9586:9586
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped  
    
networks:
  telemt-network:
    driver: bridge